### ISSUE TITLE
[Solved]AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by huchi00057** [huchi00057/YOLOX#2]
Traceback (most recent call last):
    File "D:\yolox\tools\demo.py", line 388, in <module>
      main(exp, args)
    File "D:\yolox\tools\demo.py", line 379, in main
      image_demo(predictor, vis_folder, args.path, current_time, args.save_result)
    File "D:\yolox\tools\demo.py", line 197, in image_demo
      outputs, img_info = predictor.inference(image_name)
    File "D:\yolox\tools\demo.py", line 143, in inference
      height, width = img.shape[:2]
  AttributeError: 'NoneType' object has no attribute 'shape'

![image](https://user-images.githubusercontent.com/46515944/182148870-8a32b4fc-ed6a-43d1-828b-eed5d2ff5d72.png)

**Comment by huchi00057** [comment]
[Solved]
Your cmd must be wrong in path of image or video.

**Comment by huchi00057** [comment]
python tools/demo.py image -f exps/example/custom/yolox_s.py -c best_ckpt.pth --path _**test/123.jpg**_  --save_result
